version: "3.8"
services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8081:8081'
    volumes:
      - ./:/app
      - ./myserver.config:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
  backend:
    build: ./
    #    build:
    #      context: ./backend
    #      dockerfile: Dockerfile
    #      args:
    #        some-arg: 1
#    ports:
#      - '8080:8080'
    volumes:
      - ./:/app